var searchData=
[
  ['vcoroutineschedule_0',['vCoRoutineSchedule',['../group__v_co_routine_schedule.html',1,'']]],
  ['vqueuedelete_1',['vQueueDelete',['../group__v_queue_delete.html',1,'']]],
  ['vsemaphorecreatebinary_2',['vSemaphoreCreateBinary',['../group__v_semaphore_create_binary.html',1,'']]],
  ['vsemaphoredelete_3',['vSemaphoreDelete',['../group__v_semaphore_delete.html',1,'']]],
  ['vstreambufferdelete_4',['vStreamBufferDelete',['../group__v_stream_buffer_delete.html',1,'']]],
  ['vtaskdelay_5',['vTaskDelay',['../group__v_task_delay.html',1,'']]],
  ['vtaskdelayuntil_6',['vTaskDelayUntil',['../group__v_task_delay_until.html',1,'']]],
  ['vtaskdelete_7',['vTaskDelete',['../group__v_task_delete.html',1,'']]],
  ['vtaskendscheduler_8',['vTaskEndScheduler',['../group__v_task_end_scheduler.html',1,'']]],
  ['vtaskgetinfo_9',['vTaskGetInfo',['../group__v_task_get_info.html',1,'']]],
  ['vtaskgetruntimestats_10',['vTaskGetRunTimeStats',['../group__v_task_get_run_time_stats.html',1,'']]],
  ['vtasklist_11',['vTaskList',['../group__v_task_list.html',1,'']]],
  ['vtaskpriorityset_12',['vTaskPrioritySet',['../group__v_task_priority_set.html',1,'']]],
  ['vtaskresume_13',['vTaskResume',['../group__v_task_resume.html',1,'']]],
  ['vtaskresumefromisr_14',['vTaskResumeFromISR',['../group__v_task_resume_from_i_s_r.html',1,'']]],
  ['vtaskstartscheduler_15',['vTaskStartScheduler',['../group__v_task_start_scheduler.html',1,'']]],
  ['vtasksuspend_16',['vTaskSuspend',['../group__v_task_suspend.html',1,'']]],
  ['vtasksuspendall_17',['vTaskSuspendAll',['../group__v_task_suspend_all.html',1,'']]]
];
